# Generated by Django 6.0.7 on 2026-07-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulante',
            old_name='mensaje',
            new_name='dificultad_actual',
        ),
        migrations.AddField(
            model_name='postulante',
            name='compromiso',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postulante',
            name='experiencia_previa',
            field=models.TextField(default='Pendiente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postulante',
            name='motivacion',
            field=models.TextField(default='Pendiente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postulante',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='objetivo',
            field=models.CharField(choices=[('Perder grasa', 'Perder grasa'), ('Ganar masa muscular', 'Ganar masa muscular'), ('Recomposición corporal', 'Recomposición corporal'), ('Mejorar rendimiento', 'Mejorar rendimiento')], max_length=100),
        ),
    ]
